#!/bin/sh

rm -fr autom4te.cache

# reconstruct gnulib files, if gnulib-tool is available
if (type -f gnulib-tool) > /dev/null 2>&1; then
    gnulib-tool --import
else
    mkdir -p libupnp/config.aux
    touch libupnp/config.aux/config.rpath
fi

# Equivalent to 
#	aclocal 
#	autoheader 
#	automake --add-missing --copy
#	autoconf

autoreconf --force --install -Wall -Wno-obsolete $* || exit 1

echo "Now run ./configure and then make."
exit 0





